### PR TITLE
Fix position naming

### LINKED ISSUE #206: [PE-D] Position value is not case insensitive
The position values are not case insensitive. 
* `Bookkeeper` is valid
* `bookkeeper` is valid
* However, `Bookkeeper` != `bookkeeper` 

Can lead to confusion

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: timothywongej/ped#7

### PR DESCRIPTION
**Pull request by sw-boi**
-Updated commands that take in position such that regardless of what the user inputs, the position that is stored has the same naming convention as the one in the positionlist.
    - e.g If BOOKkeeper is stored in the positionlist, add_c position=bookkeeper, will store BOOKkeeper inside the candidate object.

-Updated Position error messages to be stored in Position.java instead of elsewhere.
-Updated EditPosition such that is also changes the title for Interview objects
-Updated relevant test cases
-Renamed Interview::removeCandidate to Interview::deleteCandidate to be inline with other removal commands

Fix #206

### CODE REVIEW

**Review by wanyu-l — APPROVED** [review]
LGTM, only the method name "getPositionReference" is slightly confusing for me, perhaps we can change it in the future?

File: src/main/java/seedu/address/logic/position/EditPositionCommand.java [hunk 1]
```diff
@@ -100,6 +101,13 @@ public CommandResult execute(Model model) throws CommandException {
             }
         }
 
+        for (Interview interview : lastShownInterviewList) {
+            Position interviewPosition = interview.getPosition();
+            if (interviewPosition.isSamePosition(positionToEdit)) {
+                interview.setPosition(editedPosition);
+            }
+        }
+
```
Comment (wanyu-l) [inline src/main/java/seedu/address/logic/position/EditPositionCommand.java:110]: Currently edit_p does not have immediate GUI update, perhaps can add 
"model.updateFilteredInterviewList(PREDICATE_SHOW_ALL_INTERVIEWS);"

Comment (wanyu-l) [reply src/main/java/seedu/address/logic/position/EditPositionCommand.java:110]: Oh wait it is handled by your other PR never mind just ignore this
